### ISSUE TITLE
SKELify Female

### ISSUE THREAD

**Issue by DHPark98** [IsshikiHugh/HSMR#34]
Thank you for your great work!
I have a simple question.

From what I can tell by checking the configuration file below, the checkpoint used in the demo appears to be the one trained with male data:

[data_inputs/released_models/HSMR-ViTH-r1d1/.hydra/config.yaml]
```
( ... )
  models:
    body_models:
      skel_mix_hsmr:
        _target_: lib.body_models.skel_wrapper.SKELWrapper
        model_path: ${_pm_.inputs}/body_models/skel
        gender: male
        joint_regressor_extra: ${_pm_.inputs}/body_models/SMPL_to_J19.pkl
        joint_regressor_custom: ${_pm_.inputs}/body_models/J_regressor_SKEL_mix_MALE.pkl
      skel_hsmr:
        _target_: lib.body_models.skel_wrapper.SKELWrapper
        model_path: ${_pm_.inputs}/body_models/skel
        gender: male
        joint_regressor_extra: ${_pm_.inputs}/body_models/SMPL_to_J19.pkl
      smpl_hsmr:
        _target_: lib.body_models.smpl_wrapper.SMPLWrapper
        model_path: ${_pm_.inputs}/body_models/smpl
        gender: male
        num_body_joints: 23
        joint_regressor_extra: ${_pm_.inputs}/body_models/SMPL_to_J19.pkl
( ... )
```

How can I run the demo with female inputs?
Could you also provide a checkpoint trained with female data?
